name: Deployment

on:
  workflow_call:
    inputs:
      profile:
        required: true
        type: string

jobs:
  send-message:
    name: Send update message to server
    uses: nl-squad/nl-cod2-workflows/.github/workflows/send-server-message.yml@main
    with:
      profile: default
      message: "^8[UPDATE] ^7Continous deployment ^9updated mod version"
    secrets: inherit

  deploy:
    name: Deploy server files
    runs-on: ubuntu-latest
    needs: send-message

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy server files
      run: |
        project_definition="project-definition.json"
        if [ ! -f $project_definition ]; then
            echo "Error: $project_definition doesn't exist. Please use mynl CLI tool from within NL directory."
            exit 1
        fi

        function extract_value_or_exit() {
          local key=$1
          local value=$(jq -r "$key" "$project_definition")

          if [ "$value" = "null" ]; then
              echo "Error: $key not found in the $project_definition file."
              exit 1
          fi

          echo "$value"
        }

        ###

        profile=${{ inputs.profile }}
        connection_address=$(extract_value_or_exit '.connection.address')
        connection_user=$(extract_value_or_exit '.connection.user')
        connection_key_path=~/private_key
        deployment_remote_path=$(extract_value_or_exit ".profiles.\"$profile\".remoteDeploymentPath")
        deployment_local_path=$(extract_value_or_exit ".profiles.\"$profile\".localDeploymentPath")
        exclude_list=($(jq -r ".profiles.\"$profile\".rsyncExclude | .[]" "$project_definition"))
        rsync_exclude_options=""
        for exclude_item in "${exclude_list[@]}"; do
            rsync_exclude_options+=" --exclude='$exclude_item'"
        done
        echo "Deploying to: $connection_user@$connection_address:$deployment_remote_path"
        echo "Exclude options: $rsync_exclude_options"

        echo "${{ secrets.VPS_PRIVATE_KEY }}" > $connection_key_path
        chmod 600 $connection_key_path
        echo "Private key set up"

        (cd $deployment_local_path && rsync -az -e "ssh -i $connection_key_path -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress --delete ${exclude_options[@]} ./* $connection_user@$connection_address:$deployment_remote_path)

        rm -f $connection_key_path
      env:
        PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
