name: Restart server

on:
  workflow_call:
    inputs:
      profile:
        required: true
        type: string

jobs:
  restart:
    name: Restart the server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send message to server
      run: |
        project_definition="project-definition.json"
        if [ ! -f $project_definition ]; then
            echo "Error: $project_definition doesn't exist."
            exit 1
        fi

        function extract_value_or_exit() {
          local key=$1
          local value=$(jq -r "$key" "$project_definition")

          if [ "$value" = "null" ]; then
              echo "Error: $key not found in the $project_definition file."
              exit 1
          fi

          echo "$value"
        }

        ###

        profile=${{ inputs.profile }}
        rcon=$(extract_value_or_exit ".profiles.\"$profile\".cod2.rconPassword") || { echo "Skipping - no rcon password found"; exit 0; }
        cod2_port=$(extract_value_or_exit ".profiles.\"$profile\".cod2.port") || { echo "Skipping - no cod2 port found"; exit 0; }
        connection_address=$(extract_value_or_exit '.connection.address')

        cmd="say ^8[UPDATE] ^9Server is ^7restarting^9, please use ^3/reconnect"
        echo "Executing command '$cmd' for server $connection_address:$cod2_port"
        echo -n -e "\xff\xff\xff\xffrcon $rcon $cmd" | nc -u -w 2 $connection_address $cod2_port

    - name: Send restart command
      run: |
        project_definition="project-definition.json"
        if [ ! -f $project_definition ]; then
            echo "Error: $project_definition doesn't exist. Please use mynl CLI tool from within NL directory."
            exit 1
        fi

        function extract_value_or_exit() {
          local key=$1
          local value=$(jq -r "$key" "$project_definition")

          if [ "$value" = "null" ]; then
              echo "Error: $key not found in the $project_definition file."
              exit 1
          fi

          echo "$value"
        }

        ###

        profile=${{ inputs.profile }}
        execute_path=$(extract_value_or_exit ".profiles.\"$profile\".restartPath")
        execute_docker_compose=$(extract_value_or_exit ".profiles.\"$profile\".restartDockerCompose")
        connection_address=$(extract_value_or_exit '.connection.address')
        connection_user=$(extract_value_or_exit '.connection.user')
        project=$(extract_value_or_exit ".profiles.\"$profile\".containerName")
        connection_key_path=~/private_key
        echo "Executing at location $execute_path, host: $connection_user@$connection_address"

        echo "${{ secrets.VPS_PRIVATE_KEY }}" > $connection_key_path
        chmod 600 $connection_key_path
        echo "Private key set up"

        ssh -i $connection_key_path -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $connection_user@$connection_address "\
          cd $execute_path && \
          echo 'Displaying logs...' && \
          docker service logs ${project}_${project} --raw --tail 500 || echo 'Skipping - no such container: $project' && \
          echo 'Executing ./restart.sh...' && \
          ./restart.sh $execute_docker_compose"

        rm -f $connection_key_path
      env:
        PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
