name: Save server logs

on:
  workflow_call:
    inputs:
      profile:
        required: true
        type: string

jobs:
  save-logs:
    name: Save server logs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Save logs from server
      run: |
        project_definition="project-definition.json"
        if [ ! -f $project_definition ]; then
            echo "Error: $project_definition doesn't exist. Please use mynl CLI tool from within NL directory."
            exit 1
        fi

        function extract_value_or_exit() {
          local key=$1
          local value=$(jq -r "$key" "$project_definition")

          if [ "$value" = "null" ]; then
              echo "Error: $key not found in the $project_definition file."
              exit 1
          fi

          echo "$value"
        }

        ###

        profile=${{ inputs.profile }}
        execute_path=$(extract_value_or_exit ".profiles.\"$profile\".restartPath")
        execute_docker_compose=$(extract_value_or_exit ".profiles.\"$profile\".restartDockerCompose")
        connection_address=$(extract_value_or_exit '.connection.address')
        connection_user=$(extract_value_or_exit '.connection.user')
        project=$(extract_value_or_exit ".profiles.\"$profile\".containerName")
        connection_key_path=~/private_key
        echo "Executing at location $execute_path, host: $connection_user@$connection_address"

        echo "${{ secrets.VPS_PRIVATE_KEY }}" > $connection_key_path
        chmod 600 $connection_key_path
        echo "Private key set up"

        ssh -i $connection_key_path -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $connection_user@$connection_address "\
          cd $execute_path && \
          echo 'Displaying logs...' && \
          docker service logs ${project}_${project} --raw --tail 2000 || echo 'Skipping - no such container: $project'"

          rm -f $connection_key_path
      env:
        PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
